server:
  port: 8888
spring:
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hospital?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: root
#mybatis配置
mybatis:
  #定义sql语句所在的xml文件的位置
  mapper-locations: classpath:mappings/**.xml
  type-aliases-package: com.bdqn.pojo
